# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DYFzTf7WZRzVguaDdVsmX46ZbtXR1y5P
"""

def conv(c):
 f= ((9/5)* c) + 32  
 return f


celsius = int(input()) 
fahrenheit = conv(celsius)
print(fahrenheit)



